### ISSUE TITLE
[BUG] Low grav / Slow mo times glitch

### ISSUE THREAD

**Issue by FR33K1LL** [surftimer/Surftimer-Official#129] opened 2020-05-14 23:14 UTC
**Describe the bug**
If you set your style to low grav or slow mo, then switch teams, it will keep you in the chosen style but anything the style changed (speed, gravity etc) will be reset to normal. Your time will still be set for the chosen style (lg or sm) but with the style settings for normal style. 

**Expected behavior**
When teams are switched, the chosen styles settings should remain applied and not reset to normal.

**Screenshots/Video**
[Link to video](https://streamable.com/y5m2bv)

**Plugin List**
List of all your current sourcemod plugins, if applicable to the issue.

**Timer Version**
dev 285.7

**Additional context**
Bug is also present in 285. I assume this affects all styles, but these 2 styles are the only ones that slow your speed.

**Comment by LubricantJam** [comment] 2020-05-14 23:53
This, was fixed no?

**Comment by FR33K1LL** [comment] 2020-05-15 00:25
Which video?

**Comment by LubricantJam** [comment] 2020-05-15 00:25
*Currently Uploading, taking longer than expected*

**Comment by LubricantJam** [comment] 2020-05-15 00:26
https://youtu.be/fXLJgDcihbI

**Comment by FR33K1LL** [comment] 2020-05-15 00:27
which commit are you referring to that fixed it. I can self compile and test it out

**Comment by LubricantJam** [comment] 2020-05-15 00:30
Huh, it seems it's not actually in the latest dev build yet because no one has approved my PR yet when I've asked them to 🙃.

#123 is the PR that it is in, however that's on the Command_Teleport command but it's not happening for me either way and I'm only running the multiple-fixes branch.

**Comment by FR33K1LL** [comment] 2020-05-15 00:36
Just needs one approval eh? Ok thanks @LubricantJam , ill compile that commit and try it out.

**Comment by FR33K1LL** [comment] 2020-05-16 12:08
I believe this fixes the slow mo style , but low grav is still affected on 285.95

**Comment by olokos** [comment] 2020-06-10 02:00
@FR33K1LL 
What about 1.0.1?

**Comment by qawery-just-sad** [comment] 2020-07-09 19:00
@olokos this has been fixed by @LubricantJam #123 
Tested on your server, all styles are staying after changing teams

**Comment by FR33K1LL** [comment] 2020-07-09 19:03
Last time i checked slow mo was still affected. Unless there was another update to this i missed.

**Comment by qawery-just-sad** [comment] 2020-07-09 19:23
ahh i see it works only when you are outside start zone for some reason and if you are inside it, it just resets you to normal

**Comment by Bara** [comment] 2020-09-27 11:58
Are you able to reproduce this with the latest dev Version? If you get any errors, please update or post the errors again.

Don't forget **after updating** surftimer to run the command `sm_surftimer_upgrade` and after this to [.sql](https://github.com/surftimer/Surftimer-Official/blob/dev/scripts/mysql-files/optimizations/ck_change_column_types.sql)-File.

**Comment by Kyli3Boi** [comment] 2020-10-09 20:51
Can still reproduce this

**Comment by Kyli3Boi** [comment] 2020-10-09 20:59
Tested with PR #208 and can confirm this fix works

**Closed** 2020-10-09 21:35 UTC
Labels: awaiting response, bug
