### ISSUE TITLE
[BUG] Rank 99999/ 

### ISSUE THREAD

**Issue by stunslave** [surftimer/Surftimer-Official#181] opened 2020-06-07 08:57 UTC
**Describe the bug**
Completing the map gives a rank of 99999/how many have finished.

**Screenshots**
![image](https://user-images.githubusercontent.com/47533535/83964378-ff57b200-a8ac-11ea-8c2f-ab7687bc04b9.png)
It doesn't always bring up a msg in chat/server console, but it always gives the rank of  99999/.

**Timer Version**
Prerelease 1.0.0 - development version

**Comment by sneak-it** [comment] 2020-06-07 16:08
Error logs?

**Comment by stunslave** [comment] 2020-06-07 16:17
https://github.com/surftimer/Surftimer-olokos/commit/787e5e230bccb7e124467d8ba60822934183e355 <<< this is the commit that breaks it.. 
I have recompiled the plugin with out the above commit and it works perfectly.

The error in logs if the same as above in the image.. 
https://pastebin.com/G1h2atig

**Comment by olokos** [comment] 2020-06-07 18:17
can you try this again with 1.0.1, just released?

**Comment by stunslave** [comment] 2020-06-07 18:47
https://discordapp.com/channels/366959507764674560/379572504542445568/719260398041169940
 :P

**Comment by stunslave** [comment] 2020-06-07 19:21
(Version 1.0.1) The error chat msg and the 99999 bug only happen on first completion and after finishing a map 5 or 6 times. 

If a player has already completed the map they wont get this 99999 bug nor the error msg in chat. 

![image](https://user-images.githubusercontent.com/47533535/83977781-6c963200-a903-11ea-9762-354654df85a6.png)

**Comment by olokos** [comment] 2020-06-08 15:09
I can confirm this bug
![Bug picture](https://image.prntscr.com/image/T7CSoJFQRV2X2OU7oyQpfQ.png)
I will have a look at the code later, to see what's causing it, but I have some ideas.

**Comment by olokos** [comment] 2020-06-08 15:13
![Another photo](https://image.prntscr.com/image/iRbDaLl9T7mhwx_0bBUBLg.png)
Interestingly enough, it doesn't happen for bonus zones, just the normal ones.
🤔

**Comment by olokos** [comment] 2020-06-08 15:32
Seems like upon finishing a map, when this bug occurs, no info about PB or map completed is printed.
![Bug picture](https://image.prntscr.com/image/VQZofAVJTtuSMJYi9PO7rw.png)

**Comment by olokos** [comment] 2020-06-08 15:56
Interestingly enough, I'm not getting the stack trace that you're getting.

**Comment by stunslave** [comment] 2020-06-08 20:35
If i compile the plugin without this >>>https://github.com/surftimer/Surftimer-olokos/commit/787e5e230bccb7e124467d8ba60822934183e355 It doesn't get this problem. 
I'm not a coder so I have no idea what any of this code does. Although the bots are still screwed, with or without it.

**Comment by olokos** [comment] 2020-06-10 00:09
This should help
https://forums.alliedmods.net/showthread.php?t=277525
I am too tired ATM, but this is what I will dive into.

**Comment by Kyli3Boi** [comment] 2020-06-22 23:09
I was testing this out and i too had the issue with 1.0.1 however i also experienced issues where the player would get the 9999 rank and if completed the map again, breaking the record, it would not show as rank 1 but rather rank 2,3,4,5 etc but if you disconnected and rejoined then it would show rank 1.

Due to this not showing as rank 1 that would also break the record time in chat as well as the record times. This then would ultimately break the discord announcements.

So if anyone was wondering why i said this is game breaking in the discord. This is why...

**Comment by dark-rage** [comment] 2020-08-03 20:50
Anyone found a fix for this? :(

**Comment by Kyli3Boi** [comment] 2020-08-03 21:28
Nope

**Comment by Bara** [comment] 2020-08-14 00:04
Will be fixed with #222

**Closed** 2020-09-26 18:29 UTC
Labels: 1.1.0, bug, template-unused
