### ISSUE TITLE
[BUG] Replay Bug

### ISSUE THREAD

**Issue by Ciallo-Ani** [surftimer/Surftimer-Official#135] opened 2020-05-16 15:18 UTC
**Describe the bug**
when Bot is in use,i try to reuse it one or two more times,the error can be listed as follow

L 05/16/2020 - 22:40:14: [SM] Exception reported: Invalid index 2 (count: 2)
L 05/16/2020 - 22:40:14: [SM] Blaming: add/SurfTimer.smx
L 05/16/2020 - 22:40:14: [SM] Call stack trace:
L 05/16/2020 - 22:40:14: [SM]   [0] GetArrayArray
L 05/16/2020 - 22:40:14: [SM]   [1] Line 1135, surftimer/replay.sp::PlayReplay
L 05/16/2020 - 22:40:14: [SM]   [2] Line 1095, surftimer/hooks.sp::OnPlayerRunCmd

**Timer Version**
285.9 dev

**Comment by rosekick** [comment] 2020-05-16 15:21
it almost crash my server!

**Comment by sneak-it** [comment] 2020-05-17 21:25
Possible duplicate of #54

**Comment by olokos** [comment] 2020-06-10 00:48
@rosekick 
Can you confirm this with 1.0.1?

**Comment by Bara** [comment] 2020-09-27 11:55
Are you able to reproduce this with the latest dev Version? If you get any errors, please update or post the errors again.

Don't forget **after updating** surftimer to run the command `sm_surftimer_upgrade` and after this to [.sql](https://github.com/surftimer/Surftimer-Official/blob/dev/scripts/mysql-files/optimizations/ck_change_column_types.sql)-File.

**Closed** 2021-09-06 08:17 UTC
Labels: bug, awaiting response
